### ISSUE TITLE
Split repositories

### ISSUE THREAD

**Issue by marek-saji** [marek-saji/flipping-cards#7]
Keep HTML and JavaScript in separate directories. We may have multiple repositories for different languages and such.

For a start:
1. flipping-cards-core
2. flipping-cards-jp-pl
   
   lang: jp-Kana, jp, jp-Latn, pl
   - hiragana + katakana
   - some example chapter from Minna no Nihongo
3. flipping-cards-jp-en
   
   lang: jp-Kana, jp, jp-Latn, en_GB
   - hiragana + katakana
   - some example chapter from Minna no Nihongo
# TODO
- [ ] Split
- …-core
  - [ ] flipping-cards-core website
  - [ ] Document `data-fcards` in `README.md`
  - [ ] Create `CONTRIBUTING.md`
- …-jp-pl, …-jp-en
  - [ ] Add `README.md`s
